# Please insert new items alphabetically.
backend: 
  members:
    - noahkoch
    - Yathi
    - mgraham
    - viabledish
    - benevolentmadman
    - adriaanlabusc
    - RoLoTo
    - jeradg
    - muokata
    - myeung58

  channel: '#development'

  include_repos: 
    - "pangea" 
    
  on_hold_labels:
    - hold
    - hold-wip
    - hold-blocked

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[SHUT UP SEAL]"
    - "[HOLD]"
    - "[WIP]"
    - "DO NOT MERGE"
    - "SHUT UP SEAL"
    - "HOLD"
    - "WIP"
    
  use_labels: true

  quotes:
    - I'm pretty sure there's a lot more to life than being really, really, ridiculously good looking. And I plan on finding out what that is.
    - Where shall we go for lunch?
    - Where's the data?

frontend:
  # Slack usernames
  members:
    - Yathi 
    - adriaanlabusc
    - jeradg    
    - myeung58
    - noahkoch 

  channel: "#catalog-app"

  include_repos:
    - rewardops-ng     
    - rewardops-angular-catalog
    - rewardops-angular-catalog-puntos-colombia
    - rewardops-angular-admin
    - rewardops-angular-catalog-airmiles
    - rewardops-express-admin
    - rewardops-sdk-node
    - rewardops-angular-catalog-aimia
    - rewardops-microsite-cineplex
    - rewardops-aimia-payment-form
    - rewardops-angular-catalog-puntos-colombia 

  on_hold_labels:
    - hold
    - hold-wip
    - hold-blocked

  use_labels: true

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[SHUT UP SEAL]"
    - "[HOLD]"
    - "[WIP]"
    - "DO NOT MERGE"
    - "SHUT UP SEAL"
    - "HOLD"
    - "WIP"

  quotes:
    - I'm pretty sure there's a lot more to life than being really, really, ridiculously good looking. And I plan on finding out what that is.
    - Where shall we go for lunch?
    - Where's the data?

# github handle: slack handle
slack_users:
  myeung58: "mike" 
  jeradg: "jrad"
  Yathi: "yathi"
  adriaanlabusc: "adriaan"
  noahkoch: "noah"
  mgraham: "michael"
  viabledish: "abid"
  benevolentmadman: "alex"
  RoLoTo: "rolo"
  muokata: "allan"
  kikisek: "kristyna"

gifs:
  - https://media.giphy.com/media/yoJC2iZ13CCkYd3aDK/giphy.gif
  - https://media.giphy.com/media/klwpZHP8OtuERRt78Y/giphy.gif 
  - https://media.giphy.com/media/SIa87I8SMeaUVAX3N5/giphy.gif
  - https://media.giphy.com/media/TIyJGNK325XGciFEnI/giphy.gif 
  - https://media.giphy.com/media/G3773sSDJHHy0/giphy.gif
  - https://media.giphy.com/media/6TWkEij704KHu/giphy.gif
  - https://media.giphy.com/media/VvXg0yjJQgfEQ/giphy.gif
  - https://media.giphy.com/media/xTiTnLWl6ftNuZAe8E/giphy.gif
  - https://media.giphy.com/media/3o7TKxlVXJsQsDX2og/giphy.gif
  - https://media.giphy.com/media/MQTcLpSwiFSq4/giphy.gif
  - https://media.giphy.com/media/4eOkFHBc4o5G0/giphy.gif
  - https://media.giphy.com/media/u97xNOq6ZjIuk/giphy.gif
  - https://media.giphy.com/media/IApCnLObD3jjy/giphy.gif
  - https://media.giphy.com/media/IGoAijJbQCY2A/giphy.gif
  - https://media.giphy.com/media/5xtDarlzV5lwRLdGDao/giphy.gif
  - https://media.giphy.com/media/XkFnxRgcF2RzO/giphy.gif
  - https://media.giphy.com/media/TyPKuTkBXmBPO/giphy.gif
  - https://media.giphy.com/media/EFXGvbDPhLoWs/giphy.gif
  - https://media.giphy.com/media/ZVBy1qoOHTlZK/giphy.gif
  - https://media.giphy.com/media/l46CgcFkYZ5bac89i/giphy.gif
  - https://media.giphy.com/media/8foQdeVia8DNC/giphy.gif
  - https://media.giphy.com/media/PTRuOrLT3xOUw/giphy.gif
  - https://media.giphy.com/media/4KhoXY0amVkm4/giphy.gif
  - https://media.giphy.com/media/10CbsWczvVvC3S/giphy.gif
  - https://media.giphy.com/media/lxzOwPVjTtfbO/giphy.gif
  - https://media.giphy.com/media/l41lRTRi4lYbaTTcQ/giphy.gif
  - https://media.giphy.com/media/3xz2BvJDEFMV0zCJ8s/giphy.gif
  - https://media.giphy.com/media/y2rk9njdNBblS/giphy.gif
  - https://media.giphy.com/media/3ohhwF34cGDoFFhRfy/giphy.gif
  - https://media.giphy.com/media/3ornk1yFi5KuWbMUUw/giphy.gif
  - https://media.giphy.com/media/3o7ZeAiCICH5bj1Esg/giphy.gif
